import type { PanelConfig, MapLayers } from '@/types';

// Surf vertical starts from the full variant shape so it can run from the same codebase.
// You can progressively replace panel keys/feeds with surf-specific data sources.
export const SURF_PANELS: Record<string, PanelConfig> = {
  map: { name: 'Surf Break Map', enabled: true, priority: 1 },
  'live-news': { name: 'Surf Headlines', enabled: true, priority: 1 },
  'live-webcams': { name: 'Surf Live Cams', enabled: true, priority: 1 },
  insights: { name: 'Surf AI Insights', enabled: true, priority: 1 },
  climate: { name: 'Ocean & Climate Alerts', enabled: true, priority: 1 },
  monitors: { name: 'My Surf Monitors', enabled: true, priority: 1 },
};

export const SURF_MAP_LAYERS: MapLayers = {
  conflicts: false,
  bases: false,
  cables: false,
  pipelines: false,
  hotspots: true,
  ais: true,
  nuclear: false,
  irradiators: false,
  sanctions: false,
  weather: true,
  economic: false,
  waterways: true,
  outages: false,
  cyberThreats: false,
  datacenters: false,
  protests: false,
  flights: true,
  military: false,
  natural: true,
  spaceports: false,
  minerals: false,
  fires: false,
  ucdpEvents: false,
  displacement: false,
  climate: true,
  startupHubs: false,
  cloudRegions: false,
  accelerators: false,
  techHQs: false,
  techEvents: false,
  stockExchanges: false,
  financialCenters: false,
  centralBanks: false,
  commodityHubs: false,
  gulfInvestments: false,
  positiveEvents: false,
  kindness: false,
  happiness: false,
  speciesRecovery: false,
  renewableInstallations: false,
  tradeRoutes: false,
};
